language: R
sudo: required
dist: bionic
cache: packages

apt_packages:
  - libgdal-dev
  - libproj-dev
  - libudunits2-dev

before_install:
  - sudo apt-get -qq update
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_github("r-spatial/lwgeom", ref = "467dc314a0bda011e806a8b56c8dcc153f63527c")'

env:
  global:
    - R_LIBS="http://cran.rstudio.com"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    - R_CHECK_TIMINGS_="0"

notifications:
  email:
    on_success: change
    on_failure: change
